connection: &connection
  adapter: postgresql
  host: localhost
  username: your username
  password: your password
  pool: 5
  timeout: 5000
  min_messages: warning

development:
  <<: *connection
  database: tenbest

test: &test
  <<: *connection
  database: tenbest_test

production:
  <<: *connection
  database: tenbest
