item1 = NavLink.create!( name: "Food & Drink", url: "#", active: true, position: 1, created_at: DateTime.now, updated_at: DateTime.now, icon: "icon-food", depth: 0 )
NavLink.create!( name: "Services", url: "#", active: true, position: 2, created_at: DateTime.now, updated_at: DateTime.now, icon: "icon-comp", depth: 0 )
NavLink.create!( name: "Events", url: "#", active: true, position: 3, created_at: DateTime.now, updated_at: DateTime.now, icon: "icon-mic", depth: 0 )
NavLink.create!( name: "Places", url: "#", active: true, position: 4, created_at: DateTime.now, updated_at: DateTime.now, icon: "icon-map", depth: 0 )
NavLink.create!( name: "Local Brands", url: "#", active: true, position: 5, created_at: DateTime.now, updated_at: DateTime.now, icon: "icon-rocket", depth: 0 )
sub_item1 = NavLink.create!( name: "BEST RESTAURANTS", url: "#", active: true, position: 1, created_at: DateTime.now, updated_at: DateTime.now, parent_id: item1.id, icon: "", depth: 1 )
NavLink.create!( name: "BEST BARS", url: "#", active: true, position: 2, created_at: DateTime.now, updated_at: DateTime.now, parent_id: item1.id, icon: "", depth: 1 )
NavLink.create!( name: "NIGHT CLUBS", url: "#", active: true, position: 3, created_at: DateTime.now, updated_at: DateTime.now, parent_id: item1.id, icon: "", depth: 1 )
NavLink.create!( name: "RESTAURANTS BY AREA", url: "#", active: true, position: 4, created_at: DateTime.now, updated_at: DateTime.now, parent_id: item1.id, icon: "", depth: 1 )
NavLink.create!( name: "BEST BARS BY AREA", url: "#", active: true, position: 5, created_at: DateTime.now, updated_at: DateTime.now, parent_id: item1.id, icon: "", depth: 1 )
NavLink.create!( name: "Italian Restaurants", url: "#", active: true, position: 1, created_at: DateTime.now, updated_at: DateTime.now, parent_id: sub_item1.id, icon: "", depth: 2 )
NavLink.create!( name: "Seafood", url: "#", active: true, position: 2, created_at: DateTime.now, updated_at: DateTime.now, parent_id: sub_item1.id, icon: "", depth: 2 )
NavLink.create!( name: "Indian", url: "#", active: true, position: 3, created_at: DateTime.now, updated_at: DateTime.now, parent_id: sub_item1.id, icon: "", depth: 2 )
NavLink.create!( name: "Thai", url: "#", active: true, position: 4, created_at: DateTime.now, updated_at: DateTime.now, parent_id: sub_item1.id, icon: "", depth: 2 )
NavLink.create!( name: "Chinese", url: "#", active: true, position: 5, created_at: DateTime.now, updated_at: DateTime.now, parent_id: sub_item1.id, icon: "", depth: 2 )
NavLink.create!( name: "American", url: "#", active: true, position: 6, created_at: DateTime.now, updated_at: DateTime.now, parent_id: sub_item1.id, icon: "", depth: 2 )